jobs:
- task: InstallSSHKey@0
  inputs:
    knownHostsEntry: 'github.com,192.30.252.130 ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ=='
    sshPublicKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDP3hzDoNuWicsnQxkXByej5PRwnL4x9OSu+AwfGDitHkYrKGFm6NAvwvPm7ZwucWI7RdA6RHxFWXbCR0LI/o/TO5skrf+TObV7oduaEngFsnSEsX04g9lQLlu563Q6N/biwCg1SiefH+JgKoLSStZ/SsiD43iLMkk737bU8l4xk1gXHyfCTfTIAQ2GFuFgapVnb7GNbJ2DpVEcl9M/qbkLgjHWuP1Q716rGwy8gQQ88hApuXTrgR4XWVnjgG64jpEDfmUUvlGZ8PseIsmgitx6e5KKCPP4W6F54EJZR3Dx5J2lf443OUpKU96JX2CdkAitQbq7bmYP6SZbYXoUEizL FigBug@github.com'
    sshKeySecureFile: '-----BEGIN RSA PRIVATE KEY----- Proc-Type: 4,ENCRYPTED DEK-Info: AES-128-CBC,383AE8E1FCA341D69479E9E9FF2D3E8B  d57xe03uECGPxGt0kxAGXsE3NX73r+CrklF0AST+dYAR4a7mT4BemmbvY6GGOga5 78HlRXhDhbd54vygXLyCaCQENhaHu2/kYAzD9T/kBkHAyhtg5knvFZQ5Gp5ah3qf aPFyu1UItXYQudRryCiKJCWRNCr5sEgfTEMrsIGzcnxUejg+KU/LkSQ6sZLyaQ0+ stqDoqhlwGYv7uI0uh0spIti2ZCdYRc612zToij5jYqCvXqVc5n0yFYIvwNS1noh HkTLVBU8KeV48vq8oSJt7LsH6ElY/pHxgsB6va7CD3r65ynczfkfM4F9Bj6P20JR 2i34thXSc74B14pqXOJWqqJeDOsHLhaj14PxMhvhJ8bZYarsrQHuSGZB2FHG0MD0 NeM2IqSjoLTZc+FGJMd3AZN4bzH+18RON8Hws4mjyqmm+3V+3R3qpRRJLdqVQ8iO HuHyVFgZyLdff0FcmRUzn/Hk+Hoj2UygKLFGdCn6W4x8ruGddiayEtkfmXZh5XQf QXn3ifGx64bfnvfXMGtLzMHmg+5eLRt6w72g4/ocB9I/FbJwXP2xS+dgV9SEJMQ0 1AixLoyMVGDV1HVA/J2fHT7ToywW5rTzDCepnHu7lipKeg3X6jnzgvtaxdtvSezv abDKIRav05cIih2AFarmjReS2k7D/ylDGJpA7qNK0ktRv3jXivCl4eRpDcN5G0yH RW+TdeMShADD9KtfiME2Rv4sFKd5QdDAtMhjn3x1CouZ3gQyw3mEvPOjXoDrd9Hy AC4zhTwkHAYTGG3qjqcWS++FgoIkb64EDKpH4ZQr2MFW0v1ZpyeXgEqFxiMaN80z 4ZuoJy69v3b6GJKtneFF2PKHaRGlJY1UWuayToNVXsCcQ7F/UDKCbrt/Gkepk/lM D6jwq2lB/1N8S3MYFz0dIsUl1ntbw9CUwxQn6w7hFA+3EgK0v/Ftp4Gy6C3QHQxN hSLQMVMPJbhCYIkqE+ALpHXzh+a8ZwHoX07BwtPt0NrjlfasUq0Hbj33ihP/TrYZ Bt9KwtPco0yYxukNzSonLSowBjMljnq916p0RgwKX8YgRhJTfPtDBLnVZDKM977q ZKbGmMX9skLDPoYmtvc7EmpShkmv8ab0ohP/pmcjUa7FcwCbvr0pJ55QqFJNDP60 Jx24oWJvO4zgyouYeBNPzWFegndmhdSB7XzQl5voMFcVn10w6zUF2Dr9iy6FXNYK fC7GOo35u6js4rkbcOaWjesN89AEw7DgUCcsnJO/S5d2EhavpHJKxpyZ0MUocpsQ RLmeH/bWC0pbBlviBoZBcoyWUYkLxrn5KBqrBwc51vIIaO6Ljv4cNAIEf0Lv44cB 5eQVODAeJYVNZaQ3HrCv2P08L1dzER++UfSoDphPje+kvvzyYhF+aCGLfOOWj7p+ RbR+dU0m35PBhM1MKcmZQVeg7hWeotchNfXqrXk++oFz4wi/UJrnULoNAe/FjHUj 8bSRwW1DkZpMDJHELC5mxojm3C061Q7MZ6ERWnUgjpko9jj0NYFinb+mKJWBgwAk trBadeH3kuDnvTjm5ayuFj7czQR3zAZ03qlioMPXZm2zWXhkcepJ8U0wJpl+MfAl -----END RSA PRIVATE KEY-----'
- job: macOS
  pool:
    vmImage: 'macOS-10.14'
  steps:
  - checkout: self
    submodules: true
    persistCredentials: true
  - script: Scripts/macci
    displayName: 'macOS Build'
  - task: PublishPipelineArtifact@0
    inputs:
      artifactName: 'macOS'
      targetPath: 'Scripts/bin/mac'
#- job: windows
#  pool:
#    vmImage: 'vs2017-win2016'
#  steps:
#  - script: |
#      set MSBUILD_EXE=C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\MSBuild.exe
#      Scripts/winci
#    displayName: 'Windows Build'
#  - task: PublishPipelineArtifact@0
#    inputs:
#      artifactName: 'Windows'
#      targetPath: '/Scripts/bin/windows'
